"""Generate per-agent launcher scripts for external CLI agents.

Scripts are written to data/relay/ on first Relay start.
Each script: registers MCP, launches the CLI inside a queue watcher,
injects "check relay - use mcp" into the terminal on @mention triggers.
"""

import json
from pathlib import Path


# Wake prompt injected into agent terminal on @mention
_WAKE_PROMPT = "check relay - use mcp"

_AGENT_DEFAULTS = {
    "claude": {
        "command":      "claude",
        "color":        "#a78bfa",
        "label":        "Claude",
        "mcp_register": 'claude mcp add relay --transport http http://127.0.0.1:8200/mcp',
        "resume_flag":  "--resume",
        "transport":    "http",
    },
    "codex": {
        "command":      "codex",
        "color":        "#facc15",
        "label":        "Codex",
        "mcp_register": None,   # uses .mcp.json
        "resume_flag":  "exec resume",
        "transport":    "http",
    },
    "kimi": {
        "command":      "kimi",
        "color":        "#38bdf8",
        "label":        "Kimi",
        "mcp_register": None,   # uses .mcp.json
        "resume_flag":  "--resume",
        "transport":    "http",
    },
    "gemini": {
        "command":      "gemini",
        "color":        "#4285f4",
        "label":        "Gemini",
        "mcp_register": None,   # uses .gemini/settings.json
        "resume_flag":  "--resume",
        "transport":    "sse",
    },
}

_MCP_JSON_HTTP = {
    "mcpServers": {
        "relay": {
            "type": "http",
            "url":  "http://127.0.0.1:8200/mcp",
        }
    }
}

_MCP_JSON_SSE = {
    "mcpServers": {
        "relay": {
            "type": "sse",
            "url":  "http://127.0.0.1:8201/sse",
        }
    }
}

_WINDOWS_BAT = """\
@echo off
setlocal

:: Monolith Relay launcher — {label}
:: Generated by Monolith Relay. Re-run to regenerate.

set RELAY_DATA=%~dp0
set QUEUE_FILE=%RELAY_DATA%{name}_queue.jsonl
set WAKE_PROMPT={wake_prompt}
set CLI_CMD={command}

:: Register MCP (idempotent)
{mcp_register_cmd}

:: Write .mcp.json if needed
{mcp_json_cmd}

:: Start CLI in a new window alongside watcher
echo Starting {label}...
start "" cmd /k "%CLI_CMD%"

:: Queue watcher — injects wake prompt when queue file has content
:watch
timeout /t 1 /nobreak >nul
if exist "%QUEUE_FILE%" (
    for /f "usebackq" %%i in ("%QUEUE_FILE%") do (
        echo Wake trigger for {label}
    )
    del "%QUEUE_FILE%" >nul 2>&1
)
goto watch
"""

_UNIX_SH = """\
#!/usr/bin/env bash
# Monolith Relay launcher — {label}
# Generated by Monolith Relay. Re-run to regenerate.

RELAY_DATA="$(dirname "$0")"
QUEUE_FILE="$RELAY_DATA/{name}_queue.jsonl"
WAKE_PROMPT="{wake_prompt}"
CLI_CMD="{command}"
SESSION_NAME="relay-{name}"

# Register MCP / write config
{mcp_setup}

# Start agent in a tmux session
if tmux has-session -t "$SESSION_NAME" 2>/dev/null; then
    echo "{label} tmux session already running. Attaching..."
else
    tmux new-session -d -s "$SESSION_NAME" "$CLI_CMD"
    echo "{label} started in tmux session: $SESSION_NAME"
    echo "Detach: Ctrl+B, D  |  Reattach: tmux attach -t $SESSION_NAME"
fi

# Queue watcher — injects wake prompt via tmux send-keys
while true; do
    sleep 1
    if [ -f "$QUEUE_FILE" ]; then
        while IFS= read -r line; do
            [ -n "$line" ] && tmux send-keys -t "$SESSION_NAME" "$WAKE_PROMPT" Enter
        done < "$QUEUE_FILE"
        rm -f "$QUEUE_FILE"
    fi
done
"""


def generate(output_dir: Path) -> None:
    """Write all launcher scripts and a README to output_dir."""
    output_dir.mkdir(parents=True, exist_ok=True)

    for name, cfg in _AGENT_DEFAULTS.items():
        _write_windows(output_dir, name, cfg)
        _write_unix(output_dir, name, cfg)

    # .mcp.json for codex/kimi (HTTP)
    mcp_json_path = output_dir / "mcp.json"
    mcp_json_path.write_text(json.dumps(_MCP_JSON_HTTP, indent=2), "utf-8")

    # .gemini/settings snippet
    gemini_json_path = output_dir / "gemini_settings_snippet.json"
    gemini_json_path.write_text(json.dumps(_MCP_JSON_SSE, indent=2), "utf-8")

    # README
    _write_readme(output_dir)


def _mcp_register_cmd_windows(name: str, cfg: dict) -> tuple[str, str]:
    """Return (mcp_register_line, mcp_json_line) for Windows bat."""
    if cfg["mcp_register"]:
        return cfg["mcp_register"], ":: (no .mcp.json needed)"
    if cfg["transport"] == "sse":
        return (
            ":: Gemini: copy gemini_settings_snippet.json to .gemini\\settings.json",
            ":: See relay_data\\gemini_settings_snippet.json",
        )
    return (
        ":: Writing .mcp.json for MCP registration",
        f'echo {json.dumps(json.dumps(_MCP_JSON_HTTP))} > .mcp.json',
    )


def _write_windows(out: Path, name: str, cfg: dict) -> None:
    reg, mcpj = _mcp_register_cmd_windows(name, cfg)
    content = _WINDOWS_BAT.format(
        label=cfg["label"],
        name=name,
        wake_prompt=_WAKE_PROMPT,
        command=cfg["command"],
        mcp_register_cmd=reg,
        mcp_json_cmd=mcpj,
    )
    (out / f"start_{name}.bat").write_text(content, "utf-8")


def _write_unix(out: Path, name: str, cfg: dict) -> None:
    if cfg["transport"] == "sse":
        mcp_setup = (
            "# Gemini: copy gemini_settings_snippet.json to .gemini/settings.json\n"
            "# cp \"$RELAY_DATA/gemini_settings_snippet.json\" .gemini/settings.json"
        )
    elif cfg["mcp_register"]:
        mcp_setup = cfg["mcp_register"]
    else:
        mcp_setup = (
            "# Writing .mcp.json\n"
            f"echo '{json.dumps(_MCP_JSON_HTTP)}' > .mcp.json"
        )

    content = _UNIX_SH.format(
        label=cfg["label"],
        name=name,
        wake_prompt=_WAKE_PROMPT,
        command=cfg["command"],
        mcp_setup=mcp_setup,
    )
    path = out / f"start_{name}.sh"
    path.write_text(content, "utf-8")
    try:
        import os
        path.chmod(path.stat().st_mode | 0o111)
    except Exception:
        pass


def _write_readme(out: Path) -> None:
    readme = """\
# Monolith Relay — External Agent Launchers

Run the appropriate script to connect an external CLI agent to Relay.

## Windows
- start_claude.bat   — Claude Code  (HTTP MCP :8200)
- start_codex.bat    — Codex        (HTTP MCP :8200)
- start_kimi.bat     — Kimi         (HTTP MCP :8200)
- start_gemini.bat   — Gemini       (SSE  MCP :8201)

## macOS / Linux (requires tmux)
- start_claude.sh
- start_codex.sh
- start_kimi.sh
- start_gemini.sh

## Manual MCP registration

Claude Code:
  claude mcp add relay --transport http http://127.0.0.1:8200/mcp

Codex / Kimi — add to .mcp.json in your project root:
  (copy mcp.json provided here)

Gemini — add to .gemini/settings.json:
  (copy gemini_settings_snippet.json provided here)

## Wake prompt
When @mentioned, the watcher injects:
  check relay - use mcp
into the agent's terminal automatically.
"""
    (out / "README.txt").write_text(readme, "utf-8")
